# Generated by Django 4.2.11 on 2024-07-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo_fence_operations", "0002_geofence_is_test_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="geofence",
            name="message",
            field=models.CharField(blank=True, help_text="Set the status regarding the availability of the dataset", max_length=140, null=True),
        ),
        migrations.AddField(
            model_name="geofence",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Activating"), (1, "Ready"), (3, "Deactivating"), (4, "Unsupported"), (5, "Rejected"), (6, "Error")], default=0
            ),
        ),
    ]
