# Generated by Django 4.2.1 on 2023-06-02 10:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flight_declaration_operations', '0003_alter_flightdeclaration_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightdeclaration',
            name='aircraft_id',
            field=models.CharField(default='000', help_text='Specify the ID of the aircraft for this declaration', max_length=256),
        ),
        migrations.AddField(
            model_name='flightdeclaration',
            name='latest_telemetry_datetime',
            field=models.DateTimeField(blank=True, help_text='The time at which the last telemetry was received for this operation, this is used to determine operational conformance', null=True),
        ),
        migrations.CreateModel(
            name='FlightAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declaration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flight_declaration_operations.flightdeclaration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
