# Generated by Django 4.2.1 on 2023-06-08 16:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flight_declaration_operations', '0005_flightauthorization_dss_operational_intent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightOperationTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.CharField(blank=True, help_text='Entry notes', max_length=512, null=True, verbose_name='Notes')),
                ('deltas', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_declaration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_info', to='flight_declaration_operations.flightdeclaration')),
            ],
        ),
    ]
