# Generated by Django 4.2.3 on 2023-08-02 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("flight_declaration_operations", "0006_flightoperationtracking"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskScheduler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flight_declaration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="flight_declaration_operations.flightdeclaration",
                    ),
                ),
                (
                    "periodic_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.periodictask",
                    ),
                ),
            ],
        ),
    ]
